### ISSUE TITLE
Possible feature : A shim for ES6 Proxy

### ISSUE THREAD

**Issue by sebilasse** [dojo/shim#12]
seeAlso: https://github.com/GoogleChrome/proxy-polyfill
reason: http://caniuse.com/#search=Proxy

**Comment by kitsonk** [comment]
@sebilasse we had avoided tackling this because `Proxy` is not fully polyfillable and we haven't found a specific use case in the rest of Dojo 2 yet that would warrant the investment.

In what you are looking at/doing, how big of a priority is a partial shim?  What sort of patterns would you like to use it with where you don't have a decent alternative?

This would help us give it the right sort of priority.

**Comment by kitsonk** [comment]
Going to close until we have a strong use case for Proxy.  I am still not aware of one.
