### ISSUE TITLE
Array 'from' typing prevents polymorphism

### ISSUE THREAD

**Issue by novemberborn** [dojo/shim#3]
This is not allowed with `from()`:

``` ts
interface Combined = {
  key: string;
  value: number;
}

const map = new Map<string, number>();
const arr: Combined[] = from(map, ([key, value]) => ({ key, value }));
```

Here the "arrayLike" type is different from the "mapFunction" element type, which is different from the return value.

The types in question:

``` ts
from<T>(arrayLike: Iterable<T> | ArrayLike<T>, mapFunction?: MapCallback<T>, thisArg?: {}): Array<T>;
MapCallback<T>(element: T, index: number): T;
```

I'm not sure if this stuff could even be inferred, but you need a good amount of `any` hammers and type casting to get around it:

``` ts
const arr = from<Combined>(<any> map, (entry: any) => {
  const [key, value] = <[string, number]> entry;
  return { key, value };
});
```

**Comment by kitsonk** [comment]
Yeah, it looks like we don't have the optimal typings.  It can be inferred and [`lib.es2015.core.d.ts`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.core.d.ts#L71) has better typings for this:

``` typescript
from<T, U>(arrayLike: ArrayLike<T>, mapfn: (v: T, k: number) => U, thisArg?: any): Array<U>;
```

**Comment by kitsonk** [comment]
The trick is that the `mapFn` needs to be a required parameter in an overload.

**Comment by novemberborn** [comment]
Oh nice!

Would that infer `Map[Symbol.iterator]` for `T`?

**Comment by kitsonk** [comment]
Yes, it should unwrap the type, because of the typing on the [`Map.prototype[Symbol.iterator]`](https://github.com/dojo/shim/blob/31df4c3563f15b0cce33d612a8aa2b1574b56cae/src/Map.ts#L195) though we may need to do like TypeScript and merge everything into `ArrayLike` so they get unwrapped and just make sure our shims fallback properly to looping over things when there is no shimmed iterator interface.  I think I am going to open another issue for the handling of the iterators, because I think I realised the "mistakes" I made in how to handle Arrays and other Array like structures where we don't shim the `[Symbol.iterator]`.  Because even `arguments` should be  able to be passed into something like `new Set(arguments)` and "just work™".

**Comment by kitsonk** [comment]
Also, outside of cleaning stuff up though, the resulting array wouldn't be like you have it type in the first example.  At [run-time under ES2015](https://jsfiddle.net/31nvumdf/) and the shim, the resulting type is actually this:

``` typescript
type Combined = [ string, number ];
const arr: Combined[] = from(map, ([key, value]) => ({ key, value }));
```

**Comment by novemberborn** [comment]
No, you forgot the map function: https://jsfiddle.net/uv7vwbyh/1/

**Comment by kitsonk** [comment]
Oh, yeah... nevermind! Yes, it should "just work™" once we fix type typings and whatever type that is returned from the map function will work... it should be able to contextually figure it out.
