### ISSUE TITLE
Immutable and Iterator Compatibility

### ISSUE THREAD

**Issue by kitsonk** [dojo/shim#31]
@kitsonk commented on [Mon Jun 13 2016](https://github.com/dojo/core/issues/169)

For some reason, the `Iterator` interfaces between our polyfills and Immutable.js doesn't seem to work together... for example, I get a design time error with something like this, but at run-time (even on IE10) it works perfectly fine:

``` typescript
import { Map } from 'immutable/immutable';
import { from as arrayFrom } from 'dojo-core/array';

const map = Map().set('foo', {});
const keys = arrayFrom(map.keys()); // Argument of type 'Iterator<string>' is not assignable to parameter of type 'Iterable<{}> | ArrayLike<{}>'.
```

I am not entirely sure, but it seems that something is causing TypeScript to think that the `Iterator` interface from Immutable isn't an `Iterable`. 😞 

---

@mwistrand commented on [Mon Jun 13 2016](https://github.com/dojo/core/issues/169#issuecomment-225591090)

We may want to take some time to review the places we use `Iterable` instead of `Iterator`, since those two things are not the same. `dojo-core/iterator`'s definition of `interface Iterator` is compatible with that defined by Immutable.js, but `dojo-core/iterator` defines an `Iterable` as an object with its `Symbol.iterator` property set to an `Iterator` instance. I will be the first to admit that differentiating between the two can get hairy.

---

@kitsonk commented on [Mon Jun 13 2016](https://github.com/dojo/core/issues/169#issuecomment-225605295)

Hmmm... yeah, you are right... The other challenge, with TypeScript and the whole situation is that the well-known Symbols have to come from the global `Symbol` even when you are trying to polyfill things, because of the need to be assured that the referenced symbol is the correct referenced symbol.

The good news, as I said, is that it seems to be working at run-time.

**Comment by kitsonk** [comment]
This is something we should fix, it is essentially some adjustments to the iterator typings.  We can validate and align them to the TypeScript ones.

**Comment by rorticus** [comment]
# 

So in the case of the posted example,

``` js
import { Map } from 'immutable/immutable';
import { from as arrayFrom } from 'dojo-core/array';

const map = Map().set('foo', {});
const keys = arrayFrom(map.keys());
```

It looks like things aren't lining up because the Immutable typings declare `Iterator` as anything that implements the `next` method, and `Array.from` in `dojo-shim` declares that it can accept anything that has a `[Symbol.iterator]` method.

In this case I believe it is a problem of the Immutable typings being wrong, because [looking at the source](https://github.com/facebook/immutable-js/blob/master/src/Iterator.js#L38) , it looks like every Immutable iterator contains a `[Symbol.iterator]` property, which is why everything works at run-time.

I guess I’m not sure what the best way to fix this is… we could change the interface for `Array.from` to accept `IterableIterator`, but that would not line up with [the spec](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-array.from) , which specifies only that the argument should respond to `[Symbol.iterator]`.

@kitsonk , thoughts?

**Comment by kitsonk** [comment]
Considering we have decided, for now, to not depend upon ImmutableJS, I think we can just let sleeping dogs lie on this one.
