### ISSUE TITLE
Should we test shims when native features are supported?

### ISSUE THREAD

**Issue by dylans** [dojo/shim#33]
An interesting discussion point came up today which was that sometimes it is useful to be able to test a shim in Node.js to make sure the code for the test and the shim itself is accurate. However, it is not easy/obvious/well documented on how to override a static has value like you would in Dojo 1.x (I'll open a separate issue on that).

So the question is, should we test shims even when a native feature is supported, to make sure that the code for the shim and the test code to test the shim is still valid? And if so, what's the right way to handle that?

**Comment by dylans** [comment]
Actually I think it is documented at https://github.com/dojo/has#adding-a-feature-testfeature-detection ?

**Comment by kitsonk** [comment]
We should test the features across a range of platforms that fully exercise the code base.  We want to make sure there are no feature mis-alignments, so we shouldn't be testing code that isn't designed to run on a platform, because what is there to determine from that test.

As a note, there is an issue for static has features (see: dojo/has#1) and a PR outstanding that I need to dust off and write unit tests for.

**Comment by dylans** [comment]
Agreed, thanks for verifying.
