### ISSUE TITLE
Promise.all and objects as input and results

### ISSUE THREAD

**Issue by sebilasse** [dojo/shim#38]
while reading https://twitter.com/voxpelli/status/786139775212204032 :

**Version and Environment:**

Dojo2 version: v2.0.0-alpha.15

**Expected behavior:**

In https://dojotoolkit.org/reference-guide/1.10/dojo/promise/all.html the only argument to `Promise.all` could be an object OR an array

**Actual behavior:** 
An object as `Promise.all`-argument did not work.

**Comment by kitsonk** [comment]
This is because it is aligned to the ES6 format.  While I personally like the functionality too, the signature `Promise.all(iterable)`.  With shim, we should keep aligned strictly with the ES6 specification (which we are thinking about moving `Promise.prototype.finally()` to `Task`.  We could provide this functionality there as well.

**Comment by sebilasse** [comment]
It is incredible useful for me. Think exactly of the "This example demonstrates simulating 3 service requests and then performing the handling of the results in one block of code." - and think of error handling for requests. I am using it very often.
However - @kitsonk 's comment seems to be the reason why @voxpelli solved it the right way. Basically I'd like to see it in ESfuture ...

**Comment by kitsonk** [comment]
Closing and let's consider the enhancement in dojo/core#211.
